// Generated by CoffeeScript 1.3.1
(function() {
  var app, db, get_browser_name;

  app = require('express').createServer();

  db = require("redis").createClient();

  get_browser_name = function(useragent) {
    var name;
    if (useragent.indexOf('Safari') >= 0) {
      if (useragent.indexOf('Chrome') >= 0) {
        return name = 'chrome';
      } else {
        return name = 'safari';
      }
    } else if (useragent.indexOf('Firefox') >= 0) {
      return name = 'ff';
    } else if (useragent.indexOf('Opera') >= 0) {
      return name = 'opera';
    } else if (useragent.indexOf('MSIE') >= 0) {
      return name = 'msie';
    } else {
      return name = 'other';
    }
  };

  app.get('/bar_stat/session/:partner/:instid', function(req, res, next) {
    var browser, cdate, cts, day_ts, instid, partner, _ref,
      _this = this;
    instid = req.params.instid;
    partner = req.params.partner;
    browser = get_browser_name((_ref = req.headers) != null ? _ref['user-agent'] : void 0);
    console.log("new session request: " + partner + ":" + instid);
    if (!instid || !partner) {
      return;
    }
    cdate = new Date();
    cts = cdate.getTime();
    day_ts = "" + (cdate.getUTCFullYear()) + "-" + (cdate.getUTCMonth()) + "-" + (cdate.getUTCDate());
    db.sismember("partners", partner, function(err, reply) {
      if (!reply) {
        return db.sadd("partners", partner);
      }
    });
    db.incr("" + partner + "." + day_ts + ".s_count", function(err, reply) {
      return db.hmset("" + partner + "." + day_ts + ".session." + reply, {
        instid: instid,
        browser: browser,
        ts: cts
      }, function(err, reply) {
        if (err) {
          return console.log(err);
        }
      });
    });
    db.sismember("" + partner + ".users", instid, function(err, reply) {
      db.sadd("" + partner + ".users", instid);
      if (!reply) {
        return db.incr("" + partner + "." + day_ts + ".nu_count");
      }
    });
    db.sadd("" + partner + "." + day_ts + ".users", instid);
    db.incr("" + partner + "." + day_ts + ".u_count");
    return res.send('ok');
  });

  app.listen(1337);

}).call(this);
