// Generated by CoffeeScript 1.3.3
(function() {
  var bcrypt, db, partner, pwd, set_pwd;

  db = require("redis").createClient();

  bcrypt = require('bcrypt');

  set_pwd = function(partner, pwd) {
    var hash, salt;
    salt = bcrypt.genSaltSync(10);
    hash = bcrypt.hashSync(pwd, salt);
    return db.hset("partner.creds." + partner, 'hsecret', hash, function(err, reply) {
      if (err) {
        console.log(err.stack);
      } else {
        console.log('Password successfully set!');
      }
      return process.exit();
    });
  };

  partner = process.argv[2];

  pwd = process.argv[3];

  if (partner && pwd) {
    set_pwd(partner, pwd);
  } else {
    console.log("Usage:\n$ node set_pwd.js <partner_name> <new_partner_password>");
    process.exit();
  }

}).call(this);
