// Generated by CoffeeScript 1.3.3
(function() {
  var check_if_needs_auth, get_browser_name, get_db_client, get_ts_and_day_ts, redis, __;

  redis = require("redis");

  __ = require('underscore');

  exports.clean_partner_cookie = function(cookies) {
    return cookies.build = cookies.build.split('/')[0];
  };

  exports.get_db_client = get_db_client = __.memoize(function() {
    console.log('creating redis client');
    return redis.createClient();
  });

  exports.get_browser_name = get_browser_name = function(useragent) {
    var name;
    if (useragent == null) {
      useragent = '';
    }
    if (useragent.indexOf('Safari') >= 0) {
      if (useragent.indexOf('Chrome') >= 0) {
        return name = 'chrome';
      } else {
        return name = 'safari';
      }
    } else if (useragent.indexOf('Firefox') >= 0) {
      return name = 'ff';
    } else if (useragent.indexOf('Opera') >= 0) {
      return name = 'opera';
    } else if (useragent.indexOf('MSIE') >= 0) {
      return name = 'msie';
    } else {
      return name = 'other';
    }
  };

  exports.get_ts_and_day_ts = get_ts_and_day_ts = function(date) {
    var cts, day_ts;
    cts = date.getTime();
    day_ts = "" + (date.getUTCFullYear()) + "-" + (date.getUTCMonth()) + "-" + (date.getUTCDate());
    return [cts, day_ts];
  };

  exports.check_if_needs_auth = check_if_needs_auth = function(req) {
    return !(req.session.loggedin && req.session.user === req.params.partner);
  };

}).call(this);
